apiVersion: v2
appVersion: v1.14.4
version: 1.14.4
dependencies:
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
    condition: ""
    alias: cert-manager
    tags: []
    import-values: []
deprecated: false
description: Cert-Manager is a kubernetes-aware certificate manager
keywords:
  - cert-manager
  - certificates
  - security
kubeVersion: ">=1.24.0-0"
name: cert-manager
sources:
  - https://github.com/cert-manager
  - https://cert-manager.io/
type: application